### ISSUE TITLE
customize/remove footer

### ISSUE THREAD

**Issue by cod3licious** [owenh000/asciidoctor-multipage#11]
There is automatically a footer element added with something like:
```
Version 0.1
Last updated 2021-06-14 16:23:50 +0200
```

Is there a way of customizing/removing just this part? I tried adding this at the top of my main .adoc file (see [documentation](https://docs.asciidoctor.org/asciidoctor/latest/docinfo/)):
`:docinfo: shared-footer`
And while my custom footer specified in "docinfo-footer.html" was then added at the very bottom of the page, the original footer was still there right above it.

On a possibly related note, I found that the package adds this
```html
<style>.toc-current{font-weight: bold;} .toc-root{font-family: "Open Sans","DejaVu Sans",sans-serif;
                       font-size: 0.9em;} #content{display: flex; flex-direction: column; flex: 1 1 auto;}
             .nav-footer{text-align: center; margin-top: auto;}
             .nav-footer > p > a {white-space: nowrap;}</style>
```
after it includes the contents from my originally specified css file (also: not quite sure why it copies all that instead of just linking to it but ok). What is a bit annoying here is that it specifies the `font-family` for `.toc-root` and while I had specified a different font everywhere in my normal css file, this was always overwriting the settings for this individual element, which means it didn't fit to the rest of my style anymore. Maybe this could instead inherit from something else?

**Comment by owenh000** [comment]
@cod3licious, thanks for the report.

Regarding customizing the footer, please provide a brief example document. It should use the `:docinfo: shared-footer` setting in a way that works with the stock Asciidoctor single-page HTML output but does not work with the asciidoctor-multipage extension. If I understand correctly, this will require code examples for the contents of two files named `document.adoc` (or whatever) and `docinfo-footer.html`.

Regarding the CSS styling: this additional styling is used to mark the current page in the Table of Contents. I don't think it is related to the footer problem. Perhaps you could open a separate issue for this?

**Comment by cod3licious** [comment]
@owenh000 sorry, I thought since in the CSS it said something about a footer I thought it was related, but I guess this part is about the links... And I found the option to disable this part of the footer by simply using `:nofooter:` in the document setup part - apparently it was due to asciidoctor after all (https://github.com/asciidoctor/asciidoctor/issues/1621) - sorry!

I'll open a new issue for the `.toc-root` styling.

**Comment by owenh000** [comment]
Okay, thanks for the update!
