### ISSUE TITLE
`.toc-root` font should be inherited

### ISSUE THREAD

**Issue by cod3licious** [owenh000/asciidoctor-multipage#12]
asciidoctor-multipage adds this
```html
<style>.toc-current{font-weight: bold;} .toc-root{font-family: "Open Sans","DejaVu Sans",sans-serif;
                       font-size: 0.9em;} #content{display: flex; flex-direction: column; flex: 1 1 auto;}
             .nav-footer{text-align: center; margin-top: auto;}
             .nav-footer > p > a {white-space: nowrap;}</style>
```
after it includes the contents from the originally specified css file. What is a bit annoying here is that it specifies the `font-family` for `.toc-root` and while I had specified a different font everywhere in my normal css file, this was always overwriting the settings for this individual element, which means it didn't fit to the rest of my style anymore. Maybe this could instead inherit from something else?

**Comment by owenh000** [comment]
@cod3licious, thanks for opening a separate issue for this.

I suppose the solution is to append the additional styling to the default stylesheet during processing so it can be overridden as expected. It may be possible to do this in the `convert_document` method (but more investigation is needed).

**Comment by owenh000** [comment]
It is not possible for an Asciidoctor extension to extend the default stylesheet in all stylesheet modes (see the Asciidoctor [Stylesheet Modes](https://docs.asciidoctor.org/asciidoctor/2.0/html-backend/stylesheet-modes/#copy) documentation and the Asciidoctor [convert.rb](https://github.com/asciidoctor/asciidoctor/blob/v2.0.15/lib/asciidoctor/convert.rb#L125) source).

Commit d3bbb0aace2e84d00d9d352e0d20b2c0d6359921 adds a `multipage-disable-css` document attribute which disables the additional CSS rules so they don't interfere with a custom stylesheet.

**Comment by cod3licious** [comment]
@owenh000 umm... I think all that would be necessary to fix it is to set here: https://github.com/owenh000/asciidoctor-multipage/blob/master/lib/asciidoctor-multipage.rb#L611 `font-family: inherit` instead of specifying specific fonts, no?

**Comment by owenh000** [comment]
That doesn't work. `.toc-root` inherits a serif font from `body` (see [asciidoctor.css, line 204](https://github.com/asciidoctor/asciidoctor/blob/073c422/src/stylesheets/asciidoctor.css#L204)) whereas the entire Table of Contents normally uses a sans font. There is no `font-family` rule for the entire ToC; the ToC elements are styled individually. The only rule I can find that could be applied is this one ([asciidoctor.css, line 909](https://github.com/asciidoctor/asciidoctor/blob/073c422/src/stylesheets/asciidoctor.css#L909)):

```
#toc ul {
  font-family: "Open Sans", "DejaVu Sans", sans-serif;
  list-style-type: none;
}
```

But wrapping the root table entry in `ul` and `li` tags is just a hack, particularly considering that it doesn't even fix the overall problem: these CSS rules still end up overriding any custom stylesheet.

If I'm missing something, feel free to explain further.

**Comment by cod3licious** [comment]
I guess it depends on how you configure your overall stylesheet; since I had changed everything there to my preferred font, the inherit did exactly what I needed, but I suppose it might look less pretty with the default settings...

**Comment by owenh000** [comment]
Okay, that explains it. Yes, we want to make sure the default output is fully styled. Thanks for reporting this so we can support custom styling too.
