### ISSUE TITLE
Clarify usage of Cross-References

### ISSUE THREAD

**Issue by lamafab** [owenh000/asciidoctor-multipage#30]
Hi, thank you for creating this project!

I have a question regarding cross-references. When you generate the document into multiple pages, it no longer seems to be possible to refer to IDs in different files. Consider the following:

## chapter_a.adoc

```
[#section-a]
== Section A
...
```

## chapter_b.adoc

```
Please refer to section <<section-a>>.
```

When generating just one document (`$ asciidoctor main.adoc`), pressing on the hyperlink correctly directs you to the defined section. When you generate that document into multiple pages with your plugin, it no longer works. Ideally it should direct you to the other document.

Do note that I define the `main.adoc` like this:

```
include::chapter_a.doc[]
include::chapter_b.adoc[]
```

Is this feature supported? Thanks.

**Comment by lamafab** [comment]
My mistake, `<<section-a>>` actually does work. `pandoc` auto-generated `link::#section-a[]` for me, kind of missed that.

**Comment by owenh000** [comment]
Hi @lamafab, I'm glad you got it working, and thanks for the update.
