### ISSUE TITLE
Variables not substituted in TOC

### ISSUE THREAD

**Issue by d-gregorczyk** [owenh000/asciidoctor-multipage#38]
I converted a document of type _book_ that contains variables in headings, for which a TOC (aligned left) included unresolved data:

```
:var-label: FooBar

[#foobar]
=== {var-label}
```

The section heading is rendered in the TOC as `{var-label}` whereas it appears to be correctly substituted with `FooBar` within the actual content.

**Comment by owenh000** [comment]
Hi @d-gregorczyk, I'm not able to reproduce this. Please make sure you are using v0.0.16 (or unreleased v0.0.17.dev—it is identical at this moment).

If it still happens, please reopen this issue, providing a full working example document source and the full command used to test.

**Comment by d-gregorczyk** [comment]
Thanks, will do!

**Comment by rwoldu** [comment]
Hi this happened to me too.
Solution: the file containing the variables must be on the same level as the actual content files - in my case, they are referenced from the bookToc file (included),  i.e. the variables-file is now on the same level as all other "include::" files even though not visible in the content structure:

```
= Title
:sectnums:

<!---here not correct-->
...

:leveloffset: +1
include::../../../shared_files/variables.adoc[] <--here correct
include::../content/topics/introduction.adoc[]
:leveloffset: -1

...
```
