### ISSUE TITLE
Error: "Failed to execute goal de.saumya.mojo:gem-maven-plugin"

### ISSUE THREAD

**Issue by rwoldu** [owenh000/asciidoctor-multipage#40]
HI,
I have followed the instructions I have found in the Asciidoctor discussions regarding the Ruby installation: https://discuss.asciidoctor.org/Using-the-multi-page-converter-from-maven-tt8549.html#a8550 as I had the same origin problem as the author.
but now I get the following error: 
`Failed to execute goal de.saumya.mojo:gem-maven-plugin:2.0.1:initialize (install-gems) on project docs-public: Execution install-gems of goal de.saumya.mojo:gem-maven-plugin:2.0.1:initialize failed: Java returned: 1 `

do you have any idea what is causing the problem?
Thanks in advance.

**Comment by owenh000** [comment]
Hi @rwoldu, this project isn't associated with Maven or asciidoctor-maven-plugin. I am not familiar with Maven and am not able to offer any assistance with it. If you have a problem with asciidoctor-multipage that you can reproduce when it is used as described in the README, feel free to open an issue for that.

I do hope you are able to find a fix for the error!

**Comment by rwoldu** [comment]
thanks for your fast replies, sure will do so :)

**Comment by rwoldu** [comment]
> If you do find a fix, you're welcome to post it here! Also I'm willing to consider adding details to the README about using asciidoctor-multipage with asciidoctor-maven-plugin, if someone wants to contribute it. Aside from that, it's difficult for me to offer any support for Maven when I wrote and used asciidoctor-multipage without any relation to it.

a fix was implemented by extending the Maven settings.xml and adding a new profile that refers to the mavengem-repository.
See also Maven-Settings-docs: https://maven.apache.org/settings.html#repositories

```
<profile>
            <repositories>
                <repository>
                    <id>mavengems</id>
                    <url>mavengem:https://rubygems.org</url>
                </repository>
...
```
