### ISSUE TITLE
wrong permissions on /var/lib/gems/3.0.0/gems/asciidoctor-multipage-0.0.16/bin/asciidoctor-multipage ?

### ISSUE THREAD

**Issue by sijskes** [owenh000/asciidoctor-multipage#42]
after:
apt install ruby-rubygems
gem install asciidoctor-multipage

run as user:
ubuntu@u2:~$ asciidoctor-multipage 
/usr/local/bin/asciidoctor-multipage:25:in `load': cannot load such file -- /var/lib/gems/3.0.0/gems/asciidoctor-multipage-0.0.16/bin/asciidoctor-multipage (LoadError)
	from /usr/local/bin/asciidoctor-multipage:25:in `<main>'

errors.

/var/lib/gems/3.0.0/gems/asciidoctor-multipage-0.0.16/bin/asciidoctor-multipage is installed with: -rwxr-x--x permissions.

chmod +r  /var/lib/gems/3.0.0/gems/asciidoctor-multipage-0.0.16/bin/asciidoctor-multipage

fixes the problem.

**Comment by owenh000** [comment]
Thanks; this should be fixed with commit f2e205af87633c569b3cfc19f6ab14218d391821.
