### ISSUE TITLE
Cannot disable stylesheets across all pages

### ISSUE THREAD

**Issue by bostrt** [owenh000/asciidoctor-multipage#44]
I was hoping to disable stylesheets across all pages output by asciidoctor-multipage using `stylesheet!` ([as documented here](https://docs.asciidoctor.org/asciidoctor/latest/html-backend/stylesheet-modes/#disable)) but only the first page has stylesheets removed. 

I'm able to use `--no-header-footer` to remove stylesheets but this actually removes more than I intend (the entire header section). Is this an issue that would be addressable in asciidoctor-multipage? 

cc @ajitredhat

**Comment by owenh000** [comment]
@bostrt, thanks for the report. This should be fixed in v0.0.19.
