### ISSUE TITLE
Custom roles in headers generate broken TOC

### ISSUE THREAD

**Issue by jasal82** [owenh000/asciidoctor-multipage#7]
I have custom roles in my headers, something like

```
== [.breadcrumb]##InternalTest.##[.api-function]##getHelloWorld()
```

The corresponding `<span>` elements are generated but they seem to be escaped in the TOC because I get this in the output:

```
<li><a href="API_Crown_InternalTest.html#API_Function_InternalTest.getHelloWorld">&lt;span class="breadcrumb"&gt;InternalTest.&lt;/span&gt;&lt;span class="api-function"&gt;getHelloWorld()&lt;/span&gt;</a>
</li>
```

**Comment by owenh000** [comment]
Thanks for the report! This is fixed by commit b7af15cdc0f6ce12102794c06cd5fad978fd1369 and the fix is included in v0.0.7.
