### ISSUE TITLE
Attributes not substituted in TOC

### ISSUE THREAD

**Issue by rockyallen** [owenh000/asciidoctor-multipage#9]
The test file is
````
:product: Wibble
:toc: left
:numbered
= User guide

== Getting started with {product}
X

== Details
Y
````
After conversion The right hand pane (content) is correctly 

  1. Getting started with Wibble

but the left hand pane (TOC) is 

  1. Getting started with {product}

Downloaded version today (28 Feb)

Asciidoctor 2.0.12

**Comment by owenh000** [comment]
Thanks for the report! This is fixed in commit f7603659ea9589beb75aed420804b3d4fd11ae71 and the fix is included in v0.0.9.
